#!/bin/bash

platforms=(esp32\ esp8266\ pic32mz)

uartdef=$(ls /dev/tty.usbserial* 2>/dev/null)
if [[ "$uartdef" == "" ]]; then
  uartdef=$(ls /dev/tty.SLAB_USB* 2>/dev/null)
fi

if [[ " ${platforms[@]} " =~ " $1 " ]]; then
	
  if [[ " $1 " =~ " pic32mz " ]]; then
	make -f main/platform/pic32mz/init/Makefile.asm FOLDER=main/platform/pic32mz/init/ asm
	make -f main/platform/pic32mz/init/Makefile.asm FOLDER=FreeRTOS/source/portable/pic32mz asm
  fi
		
  source ./main/platform/$1/env
  
  if [[ " $1 " =~ " pic32mz " ]]; then
	  make $2 -j4 -C main/platform/$1/init UARTPORT=$uartdef
  else
	  make $2 -j4 -C main/platform/$1 UARTPORT=$uartdef
  fi
  
else
  echo "Unsupported platform"
fi
