#ifndef LORA_GATEWAY_SINGLE_CHANNEL_LORA_H_
#define LORA_GATEWAY_SINGLE_CHANNEL_LORA_H_

#include <sys/driver.h>

#define LORA_DRIVER driver_get_by_name("lora")

// Lora errors
#define LORA_ERR_KEYS_NOT_CONFIGURED (DRIVER_EXCEPTION_BASE(LORA_DRIVER_ID) | 0)
#define LORA_ERR_JOIN_DENIED (DRIVER_EXCEPTION_BASE(LORA_DRIVER_ID) | 1)
#define LORA_ERR_UNEXPECTED_RESPONSE (DRIVER_EXCEPTION_BASE(LORA_DRIVER_ID) | 2)
#define LORA_ERR_NOT_JOINED (DRIVER_EXCEPTION_BASE(LORA_DRIVER_ID) | 3)
#define LORA_ERR_NOT_SETUP (DRIVER_EXCEPTION_BASE(LORA_DRIVER_ID) | 4)
#define LORA_ERR_NO_MEM (DRIVER_EXCEPTION_BASE(LORA_DRIVER_ID) | 5)
#define LORA_ERR_CANT_SETUP (DRIVER_EXCEPTION_BASE(LORA_DRIVER_ID) | 6)
#define LORA_ERR_TX_ERROR_ACK (DRIVER_EXCEPTION_BASE(LORA_DRIVER_ID) | 7)
#define LORA_ERR_TX_ERROR (DRIVER_EXCEPTION_BASE(LORA_DRIVER_ID) | 8)
#define LORA_ERR_INVALID_ARGUMENT (DRIVER_EXCEPTION_BASE(LORA_DRIVER_ID) | 9)
#define LORA_ERR_INVALID_DR (DRIVER_EXCEPTION_BASE(LORA_DRIVER_ID) | 10)
#define LORA_ERR_INVALID_BAND (DRIVER_EXCEPTION_BASE(LORA_DRIVER_ID) | 11)
#define LORA_ERR_NOT_ALLOWED (DRIVER_EXCEPTION_BASE(LORA_DRIVER_ID) | 12)
#define LORA_ERR_INVALID_FREQ (DRIVER_EXCEPTION_BASE(LORA_DRIVER_ID) | 13)
#define LORA_ERR_CRYPTO_ERROR (DRIVER_EXCEPTION_BASE(LORA_DRIVER_ID) | 14)
#define LORA_ERR_TIMEOUT (DRIVER_EXCEPTION_BASE(LORA_DRIVER_ID) | 15)

extern const int lora_errors;
extern const int lora_error_map;

driver_error_t *lora_gw_setup(int band, const char *host, int port, int frequency, int drate);

#endif /* LORA_GATEWAY_SINGLE_CHANNEL_LORA_H_ */
