#define SLUA_COMMAND_CAT 257
#define SLUA_COMMAND_CD 258
#define SLUA_COMMAND_CLEAR 259
#define SLUA_COMMAND_CP 260
#define SLUA_COMMAND_DMESG 261
#define SLUA_COMMAND_EDIT 262
#define SLUA_COMMAND_EXIT 263
#define SLUA_COMMAND_LS 264
#define SLUA_COMMAND_MORE 265
#define SLUA_COMMAND_MKDIR 266
#define SLUA_COMMAND_MV 267
#define SLUA_COMMAND_PWD 268
#define SLUA_COMMAND_RM 269
#define SLUA_ARGUMENT 270
#define SLUA_EOL 271
#define SLUA_FILE 272
#ifdef YYSTYPE
#undef  YYSTYPE_IS_DECLARED
#define YYSTYPE_IS_DECLARED 1
#endif
#ifndef YYSTYPE_IS_DECLARED
#define YYSTYPE_IS_DECLARED 1
typedef union  {char *string;} YYSTYPE;
#endif /* !YYSTYPE_IS_DECLARED */
extern YYSTYPE yylval;
