SPIFFS_IMAGE_COMPONENT_PATH := $(COMPONENT_PATH)

.PHONY: flashfs

flashfs: $(SDKCONFIG_MAKEFILE) mkspiffs
	@echo "Making spiffs image ..."
	$(MKSPIFFS_COMPONENT_PATH)/../mkspiffs/src/mkspiffs -c $(SPIFFS_IMAGE_COMPONENT_PATH)/image -b 8192 -p 256 -s 0x80000 $(BUILD_DIR_BASE)/spiffs_image.img
