ifdef CONFIG_LUA_RTOS_LUA_USE_SOCKET

COMPONENT_SRCDIRS := .
COMPONENT_ADD_INCLUDEDIRS := .
COMPONENT_ADD_FS += fs
COMPONENT_ADD_LDFLAGS = -Wl,--whole-archive -l$(COMPONENT_NAME) -Wl,--no-whole-archive

else

COMPONENT_SRCDIRS :=
COMPONENT_ADD_INCLUDEDIRS :=

endif 