idf_build_get_property(python PYTHON)
idf_build_get_property(project_path PROJECT_DIR)

# Get the flash size
set(CONFIG_LUA_RTOS_FLASH_SIZE 4194304)

if("$(CONFIG_ESPTOOLPY_FLASHSIZE_1MB)" EQUAL "y")
  set(CONFIG_LUA_RTOS_FLASH_SIZE 1048576)
endif()

if("$(CONFIG_ESPTOOLPY_FLASHSIZE_2MB)" EQUAL "y")
  set(CONFIG_LUA_RTOS_FLASH_SIZE 2097152)
endif()

if("$(CONFIG_ESPTOOLPY_FLASHSIZE_4MB)" EQUAL "y")
  set(CONFIG_LUA_RTOS_FLASH_SIZE 4194304)
endif()

if("$(CONFIG_ESPTOOLPY_FLASHSIZE_8MB)" EQUAL "y")
  set(CONFIG_LUA_RTOS_FLASH_SIZE 8388608)
endif()

if("$(CONFIG_ESPTOOLPY_FLASHSIZE_16MB)" EQUAL "y")
  set(CONFIG_LUA_RTOS_FLASH_SIZE 16777216)
endif()

add_custom_command(OUTPUT "${project_path}/${CONFIG_PARTITION_TABLE_CUSTOM_FILENAME}"
  COMMAND ${python} ${project_path}/boards/gen_part.py
          -LUA_RTOS_PARTITION_TABLE_OFFSET=${CONFIG_PARTITION_TABLE_OFFSET}
          -LUA_RTOS_FLASH_SIZE=${CONFIG_LUA_RTOS_FLASH_SIZE}
          -LUA_RTOS_USE_OTA=${CONFIG_LUA_RTOS_USE_OTA}
          -LUA_RTOS_USE_FACTORY_PARTITION=${CONFIG_LUA_RTOS_USE_FACTORY_PARTITION}
          -LUA_RTOS_PART_STORAGE_SIZE=${CONFIG_LUA_RTOS_PART_STORAGE_SIZE}
          -LUA_RTOS_PART_NVS_SIZE=${CONFIG_LUA_RTOS_PART_NVS_SIZE}
          -LUA_RTOS_USE_FAT=${CONFIG_LUA_RTOS_USE_FAT}
          -LUA_RTOS_USE_SPIFFS=${CONFIG_LUA_RTOS_USE_SPIFFS}
          -LUA_RTOS_USE_LFS=${CONFIG_LUA_RTOS_USE_LFS}
          -LUA_RTOS_PARTION_CSV=${project_path}/${CONFIG_PARTITION_TABLE_CUSTOM_FILENAME}
          -LUA_RTOS_PHY_INIT_DATA_IN_PARTITION=${CONFIG_ESP32_PHY_INIT_DATA_IN_PARTITION}

  VERBATIM
)

add_custom_target(gen-part
  DEPENDS "${project_path}/${CONFIG_PARTITION_TABLE_CUSTOM_FILENAME}"
)