-- system.lua
--
-- This script is executed after a system boot or a system reset and is intended
-- to config Lua RTOS

-- DO NOT EDIT THIS FILE. TO CHANGE THE DEFAULT CONFIGURATIONS EDIT THE config.lua
-- FILE

-- Config table
config = {
	shell = true,
	history = true,	
	loglevel = os.LOG_INFO,
	logcons = true,
	wifi = false,
	ap = false,
	ethernet = false,
	sntp = false,
	http = false,
	net = {
		wifi = nil,
		ethernet = nil
	},
	data = {}
}

-- Default wifi config
config.data.wifi = {
	ssid = "",
	pass = "",
	ip = nil,
	mask = nil,
	gw = nil,
	dns1 = nil,
	dns2 = nil
}

-- Default ethernet config
config.data.ethernet = {
	ssid = "",
	pass = "",
	ip = nil,
	mask = nil,
	gw = nil,
	dns1 = nil,
	dns2 = nil
}

-- Load configution
dofile("config.lua")

if (config.wifi) then
	config.net.wifi = config.data.wifi
end

if (config.ethernet) then
	config.net.ethernet = config.data.ethernet
end

-- Network setup
if (config.wifi) then
	print("Starting wifi ...")
	net.wf.setup(
		net.wf.mode.STA, config.net.wifi.ssid, config.net.wifi.pass, 
		config.net.wifi.ip, config.net.wifi.mask, config.net.wifi.gw,
		config.net.wifi.dns1, config.net.wifi.dns2
	)
	net.wf.start()
end

if (config.ethernet) then
	print("Starting ethernet ...")
	net.en.setup(
		config.net.ethernet.ip, config.net.ethernet.mask, config.net.ethernet.gw,
		config.net.ethernet.dns1, config.net.ethernet.dns2
	)
	net.en.start()
end

-- Start network services
if (config.sntp) then
	print("Starting sntp client ...")
	net.service.sntp.start()
end

if (config.http) then
	print("Starting http server ...")
	net.service.http.start()
end

-- Main setups
os.shell(config.shell)
os.history(config.history)
os.loglevel(config.loglevel)
os.logcons(config.logcons)

config = nil