#ifndef LUA_RTOS_FIRMWARES_H_
#define LUA_RTOS_FIRMWARES_H_

#if CONFIG_LUA_RTOS_FIRMWARE_WHITECAT_ESP32_N1
#define CONFIG_LUA_RTOS_FIRMWARE "WHITECAT-ESP32-N1"
#define CONFIG_LUA_RTOS_BOARD_TYPE "N1ESP32"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE ""
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_WHITECAT_ESP32_N1_OTA
#define CONFIG_LUA_RTOS_FIRMWARE "WHITECAT-ESP32-N1-OTA"
#define CONFIG_LUA_RTOS_BOARD_TYPE "N1ESP32"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE "OTA"
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_WHITECAT_ESP32_N1_DEVKIT
#define CONFIG_LUA_RTOS_FIRMWARE "WHITECAT-ESP32-N1-DEVKIT"
#define CONFIG_LUA_RTOS_BOARD_TYPE "N1ESP32-DEVKIT"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE ""
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_WHITECAT_ESP32_N1_DEVKIT_OTA
#define CONFIG_LUA_RTOS_FIRMWARE "WHITECAT-ESP32-N1-DEVKIT-OTA"
#define CONFIG_LUA_RTOS_BOARD_TYPE "N1ESP32-DEVKIT"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE "OTA"
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_WHITECAT_ESP32_N2_DEVKIT
#define CONFIG_LUA_RTOS_FIRMWARE "WHITECAT-ESP32-N2-DEVKIT"
#define CONFIG_LUA_RTOS_BOARD_TYPE "N2ESP32-DEVKIT"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE ""
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_WHITECAT_ESP32_N2_DEVKIT_OTA
#define CONFIG_LUA_RTOS_FIRMWARE "WHITECAT-ESP32-N2-DEVKIT-OTA"
#define CONFIG_LUA_RTOS_BOARD_TYPE "N2ESP32-DEVKIT"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE "OTA"
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_WHITECAT_ESP32_LORA_GW
#define CONFIG_LUA_RTOS_FIRMWARE "WHITECAT-ESP32-LORA-GW"
#define CONFIG_LUA_RTOS_BOARD_TYPE ""
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE ""
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_WHITECAT_ESP32_LORA_GW_OTA
#define CONFIG_LUA_RTOS_FIRMWARE "WHITECAT-ESP32-LORA-GW-OTA"
#define CONFIG_LUA_RTOS_BOARD_TYPE "ESP32-LORA-GW-OTA"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE "OTA"
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_CITILAB_ED1
#define CONFIG_LUA_RTOS_FIRMWARE "CITILAB-ED1"
#define CONFIG_LUA_RTOS_BOARD_TYPE "CITILAB-ED1"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE ""
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_ESP32_CORE_BOARD
#define CONFIG_LUA_RTOS_FIRMWARE "ESP32-CORE-BOARD"
#define CONFIG_LUA_RTOS_BOARD_TYPE "ESP32COREBOARD"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE ""
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_ESP32_CORE_BOARD_OTA
#define CONFIG_LUA_RTOS_FIRMWARE "ESP32-CORE-BOARD-OTA"
#define CONFIG_LUA_RTOS_BOARD_TYPE "ESP32COREBOARD"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE "OTA"
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_ESP32_PICO_KIT
#define CONFIG_LUA_RTOS_FIRMWARE "ESP32-PICO-KIT"
#define CONFIG_LUA_RTOS_BOARD_TYPE "ESP32-PICO-KIT"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE ""
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_ESP32_PICO_KIT_OTA
#define CONFIG_LUA_RTOS_FIRMWARE "ESP32-PICO-KIT-OTA"
#define CONFIG_LUA_RTOS_BOARD_TYPE "ESP32-PICO-KIT"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE "OTA"
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_ESP_WROVER_KIT
#define CONFIG_LUA_RTOS_FIRMWARE "ESP-WROVER-KIT"
#define CONFIG_LUA_RTOS_BOARD_TYPE "ESP-WROVER-KIT"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE ""
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_ESP_WROVER_KIT_OTA
#define CONFIG_LUA_RTOS_FIRMWARE "ESP-WROVER-KIT-OTA"
#define CONFIG_LUA_RTOS_BOARD_TYPE "ESP-WROVER-KIT"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE "OTA"
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_ESP32_THING
#define CONFIG_LUA_RTOS_FIRMWARE "ESP32-THING"
#define CONFIG_LUA_RTOS_BOARD_TYPE "ESP32THING"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE ""
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_ESP32_THING_OTA
#define CONFIG_LUA_RTOS_FIRMWARE "ESP32-THING-OTA"
#define CONFIG_LUA_RTOS_BOARD_TYPE "ESP32THING"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE "OTA"
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_ADAFRUIT_HUZZAH32
#define CONFIG_LUA_RTOS_FIRMWARE "ADAFRUIT-HUZZAH32"
#define CONFIG_LUA_RTOS_BOARD_TYPE "HUZZAH32"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE ""
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_ADAFRUIT_HUZZAH32_OTA
#define CONFIG_LUA_RTOS_FIRMWARE "ADAFRUIT-HUZZAH32-OTA"
#define CONFIG_LUA_RTOS_BOARD_TYPE "HUZZAH32"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE "OTA"
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_PYCOM_FIPY
#define CONFIG_LUA_RTOS_FIRMWARE "PYCOM-FIPY"
#define CONFIG_LUA_RTOS_BOARD_TYPE "FIPY"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE ""
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_PYCOM_FIPY_OTA
#define CONFIG_LUA_RTOS_FIRMWARE "PYCOM-FIPY-OTA"
#define CONFIG_LUA_RTOS_BOARD_TYPE "FIPY"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE "OTA"
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_ESP32_POE
#define CONFIG_LUA_RTOS_FIRMWARE "ESP32-POE"
#define CONFIG_LUA_RTOS_BOARD_TYPE "ESP32-POE"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE ""
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_ESP32_POE_OTA
#define CONFIG_LUA_RTOS_FIRMWARE "ESP32-POE-OTA"
#define CONFIG_LUA_RTOS_BOARD_TYPE "ESP32-POE"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE "OTA"
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_ESP32_GATEWAY
#define CONFIG_LUA_RTOS_FIRMWARE "ESP32-GATEWAY"
#define CONFIG_LUA_RTOS_BOARD_TYPE "ESP32-GATEWAY"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE ""
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_ESP32_GATEWAY_OTA
#define CONFIG_LUA_RTOS_FIRMWARE "ESP32-GATEWAY-OTA"
#define CONFIG_LUA_RTOS_BOARD_TYPE "ESP32-GATEWAY"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE "OTA"
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_ESP32_EVB
#define CONFIG_LUA_RTOS_FIRMWARE "ESP32-EVB"
#define CONFIG_LUA_RTOS_BOARD_TYPE "ESP32-EVB"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE ""
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_ESP32_EVB_OTA
#define CONFIG_LUA_RTOS_FIRMWARE "ESP32-EVB-OTA"
#define CONFIG_LUA_RTOS_BOARD_TYPE "ESP32-EVB"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE "OTA"
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_DOIT_ESP32_DEVKIT_V1
#define CONFIG_LUA_RTOS_FIRMWARE "DOIT-ESP32-DEVKIT-V1"
#define CONFIG_LUA_RTOS_BOARD_TYPE "DOIT-ESP32-DEVKIT-V1"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE ""
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_DOIT_ESP32_DEVKIT_V1_OTA
#define CONFIG_LUA_RTOS_FIRMWARE "DOIT-ESP32-DEVKIT-V1-OTA"
#define CONFIG_LUA_RTOS_BOARD_TYPE "DOIT-ESP32-DEVKIT-V1"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE "OTA"
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_WEMOS_ESP32_OLED
#define CONFIG_LUA_RTOS_FIRMWARE "WEMOS-ESP32-OLED"
#define CONFIG_LUA_RTOS_BOARD_TYPE "WEMOS-ESP32-OLED"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE ""
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_WEMOS_ESP32_OLED_OTA
#define CONFIG_LUA_RTOS_FIRMWARE "WEMOS-ESP32-OLED-OTA"
#define CONFIG_LUA_RTOS_BOARD_TYPE "WEMOS-ESP32-OLED"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE "OTA"
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_EVK_NINA_W
#define CONFIG_LUA_RTOS_FIRMWARE "EVK-NINA-W"
#define CONFIG_LUA_RTOS_BOARD_TYPE "EVK-NINA-W"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE ""
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_WESP32
#define CONFIG_LUA_RTOS_FIRMWARE "WESP32"
#define CONFIG_LUA_RTOS_BOARD_TYPE "WESP32"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE ""
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_WESP32_OTA
#define CONFIG_LUA_RTOS_FIRMWARE "WESP32-OTA"
#define CONFIG_LUA_RTOS_BOARD_TYPE "WESP32"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE "OTA"
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_M5STACK
#define CONFIG_LUA_RTOS_FIRMWARE "M5STACK"
#define CONFIG_LUA_RTOS_BOARD_TYPE "M5STACK"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE ""
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_M5STACK_OTA
#define CONFIG_LUA_RTOS_FIRMWARE "M5STACK-OTA"
#define CONFIG_LUA_RTOS_BOARD_TYPE "M5STACK-OTA"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE ""
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_GENERIC
#define CONFIG_LUA_RTOS_FIRMWARE "GENERIC"
#define CONFIG_LUA_RTOS_BOARD_TYPE "GENERIC"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE ""
#endif

#if CONFIG_LUA_RTOS_FIRMWARE_GENERIC_OTA
#define CONFIG_LUA_RTOS_FIRMWARE "GENERIC-OTA"
#define CONFIG_LUA_RTOS_BOARD_TYPE "GENERIC"
#define CONFIG_LUA_RTOS_BOARD_SUBTYPE "OTA"
#endif

#endif